p8160\_hw4\_jsg2145
================
Jared Garfinkel
4/19/2020

``` r
blue <- c(4,69,87,35,39,79,31,79,65,95,68,
          62,70,80,84,79,66,75,59,77,36,86,
          39,85,74,72,69,85,85,72)

red <- c(62,80,82,83,0,81,28,69,48,90,63,
        77,0,55,83,85,54,72,58,68,88,83,78,
        30,58,45,78,64,87,65)

acui <- data.frame(str = c(rep(0,20),
                       rep(1,10)),
                 red,
                 blue)
```

## Part 1i

``` r
one_sui_red = acui %>% 
  filter(str == 1) %>% 
  dplyr::select(red)

one_sui_blue = acui %>% 
  filter(str == 1) %>% 
  dplyr::select(blue) %>% 
  as.tibble()
```

``` r
teststat <- function(x = pull(one_sui_red, red), y = pull(one_sui_blue, blue)) {
  return((mean(y) - mean(x))/(var(x)/length(x) + var(y)/length(y)))
}

boottest <- function(x = pull(one_sui_red, red), y = pull(one_sui_blue, blue), nboot = 200) {
  combmean <- mean(c(x, y))
  # The mean of the combined sample
  teststatvec <- rep(NA, nboot)
  adjx <- x - mean(x) + combmean
  # The adjusted X’s will have mean=combmean
  adjy <- y - mean(y) + combmean
  # The adjusted X’s will have mean=combmean
  for(b in 1:nboot) {
    teststatvec[b] <- teststat(sample(adjx, replace=T),
                               sample(adjy, replace=T))
  }
  return(list(bootpval = sum(teststat(x, y) < teststatvec)/nboot, 
              teststatvec = teststatvec))
}
```

``` r
teststat()
```

    ## [1] 0.03824062

``` r
boottest()
```

    ## $bootpval
    ## [1] 0.345
    ## 
    ## $teststatvec
    ##   [1] -3.796617e-02  7.317073e-02 -6.033250e-02 -3.943251e-02  1.235153e-01
    ##   [6] -2.427621e-02  1.551032e-01  1.631302e-01 -8.065721e-02  4.360709e-02
    ##  [11]  1.192474e-02 -1.483663e-01 -2.085550e-01  1.521684e-02  6.142297e-03
    ##  [16]  2.534552e-02 -5.010277e-02  1.862557e-01  1.365271e-02  1.199535e-01
    ##  [21] -9.038608e-02  1.867518e-02  9.323968e-02 -6.628105e-02 -1.779767e-01
    ##  [26] -1.893815e-02 -6.698298e-02 -5.761287e-02 -3.981285e-01 -1.000452e-01
    ##  [31] -1.457608e-02  5.082193e-02  1.313976e-01 -1.052426e-01 -1.026738e-01
    ##  [36] -8.419921e-02  1.279953e-01 -8.376671e-02 -4.501098e-02  1.410743e-01
    ##  [41]  1.867829e-01 -1.479919e-01  2.614759e-02 -1.805647e-01 -2.523618e-02
    ##  [46]  6.513715e-02  8.871141e-02 -9.220926e-02  3.078876e-01 -1.568713e-01
    ##  [51]  1.511335e-01 -8.644436e-02  2.013106e-01  1.307190e-01  7.067292e-02
    ##  [56] -4.397359e-02  1.972387e-01 -1.292566e-01  4.869651e-02  6.928131e-02
    ##  [61]  4.578952e-02  1.184730e-02  1.968661e-02  2.027608e-02 -4.399768e-02
    ##  [66] -7.069287e-02  1.150370e-01 -4.416685e-01 -1.062156e-01 -1.025871e-01
    ##  [71]  2.204478e-03  7.061534e-02  6.245554e-02  8.309353e-02 -8.127709e-02
    ##  [76] -4.319471e-01 -8.939859e-02 -1.706566e-01  4.103700e-02  1.203357e-01
    ##  [81] -1.348315e-01  1.777698e-02  2.078691e-02 -8.059564e-03  2.504798e-01
    ##  [86] -2.808157e-01 -1.488462e-01  2.051695e-01  7.799589e-02 -2.053787e-01
    ##  [91] -8.139555e-02 -1.310578e-03  3.119327e-02  3.088490e-02 -8.382524e-02
    ##  [96]  6.821000e-02  6.429720e-02  7.018430e-02  4.258166e-02  9.118541e-03
    ## [101]  7.682721e-02 -1.403010e-01 -1.241325e-01  1.621830e-01 -4.248447e-02
    ## [106]  4.391412e-02  1.269179e-02  1.276200e-01  1.075286e-01 -1.739864e-01
    ## [111] -7.979804e-02  2.516632e-02  1.964808e-03 -2.822810e-01  1.556674e-02
    ## [116] -9.721628e-02  1.859694e-01  2.370244e-02 -7.477225e-02 -3.459031e-02
    ## [121]  6.929535e-02 -7.552712e-02  3.488372e-02  7.953709e-02 -7.648128e-02
    ## [126]  1.070913e-01 -1.664168e-01  1.179150e-01 -1.110057e-01  2.009818e-01
    ## [131] -3.827941e-03 -1.237175e-01 -9.702327e-03 -6.690006e-02 -6.813717e-02
    ## [136]  1.174713e-01  9.094026e-02  7.749713e-02 -6.670964e-02 -2.224576e-02
    ## [141]  6.483848e-02 -1.849498e-01 -2.438546e-01 -2.094352e-02  2.091467e-01
    ## [146]  2.783320e-01 -5.499081e-01  2.240712e-01 -7.774778e-02  1.701005e-01
    ## [151]  1.081701e-01  1.917107e-01 -1.506220e-16 -5.838499e-02  1.516907e-01
    ## [156]  4.301641e-03 -3.712208e-02 -3.835727e-02  1.076959e-01 -9.997377e-02
    ## [161] -4.535098e-02  7.734617e-03 -6.259613e-02  1.279932e-01  3.787159e-02
    ## [166]  2.747765e-02  1.057145e-01  8.855846e-02  9.607943e-03  1.564654e-02
    ## [171] -9.658873e-02 -2.751747e-02  1.243764e-02 -2.417997e-01  2.797979e-01
    ## [176] -1.433343e-01 -9.483816e-02 -1.995094e-02 -2.845331e-01 -2.102118e-01
    ## [181] -8.638756e-03 -9.734875e-03 -2.165467e-01 -9.816754e-03  1.379614e-01
    ## [186] -2.749456e-02 -3.544443e-01 -1.449013e-02 -5.149044e-02  8.064516e-02
    ## [191] -1.585825e-01  9.612912e-02 -2.621246e-01 -1.876173e-01 -2.805650e-02
    ## [196]  1.430306e-01 -2.427676e-02  1.761059e-01 -1.503207e-01  3.762463e-02

``` r
paired_sample_df = acui %>% 
  filter(str == 0) %>% 
  mutate(diff = red - blue) %>%
  as.tibble()
```

``` r
set.seed(22)
teststat_paired <- function(x = pull(paired_sample_df, diff)) {
    return(mean(x)/(sqrt(var(x)/length(x))))
}

set.seed(22)
boottest_paired <- function(diff = pull(paired_sample_df, diff), nboot=200) {
  teststatvec <- rep(NA, nboot)
  adjdiff <- diff - mean(diff)
  for (b in 1:nboot) {
    teststatvec[b] <- teststat_paired(sample(adjdiff, replace = TRUE))
  }
  return(list(bootpval = sum(teststat_paired(diff) < teststatvec)/nboot, 
              teststatvec = teststatvec))
}

set.seed(22)
boottest_paired()
```

    ## $bootpval
    ## [1] 0.695
    ## 
    ## $teststatvec
    ##   [1]  0.957576295 -0.022370624 -1.054028451 -0.577034097 -1.450720899
    ##   [6] -0.024816519 -1.575152645 -2.633822752  1.704612003  0.509158683
    ##  [11]  0.460948346  2.008182888  0.804934588  0.183665916 -0.471302304
    ##  [16]  1.929950206  0.603356075 -0.111346951  0.236425088  0.229227082
    ##  [21] -0.401614992  0.117134139  1.127811764  1.426999536  1.065242616
    ##  [26]  0.774747804  0.611731503  0.028367292  1.381058734 -0.760918630
    ##  [31] -0.064634824  0.094946239  0.804864586  1.002675784  1.186610143
    ##  [36] -1.008347582  0.521854522  1.059073864 -0.499745056  1.299448399
    ##  [41] -0.542208213  1.017752975 -0.696005030  1.772556269  1.000724861
    ##  [46] -0.403687267 -0.446486363 -2.057092240 -0.298502613  0.808856226
    ##  [51] -0.288606164  1.809229192  1.958058034 -0.226639457 -0.233602846
    ##  [56] -1.470461329 -0.289839230 -0.582855294  0.068433857 -0.639584446
    ##  [61] -1.223342562 -1.138381055 -1.362016269  1.421283168  1.421950719
    ##  [66] -1.520017904  0.261891689 -2.449482898  0.744534627  1.150952309
    ##  [71] -0.308618136 -0.963926888  0.415438583 -0.417544209 -1.137254035
    ##  [76]  0.013577609 -0.062931022  0.546642067  0.048736707 -1.019026230
    ##  [81]  1.945891686 -0.806507704  0.672517057  0.983576888  0.411939767
    ##  [86] -1.348939701 -1.150283861  1.526998439  0.104940775 -0.267298285
    ##  [91]  0.529578144  1.987731620  0.249083767  0.200580367 -0.622611817
    ##  [96]  0.498845149  1.349254182  0.769015255 -2.441879724 -0.656052588
    ## [101] -2.917162029 -0.589972236 -1.219204662 -0.601381705 -0.129826419
    ## [106] -0.487663204  0.670140307 -0.778887054 -1.157142457 -0.521200111
    ## [111]  0.081959431 -0.489478707  0.632514859 -1.798208231 -0.078549346
    ## [116]  1.764412282 -0.596498778 -0.601223252 -0.457398095 -0.882080897
    ## [121]  0.164897017 -0.161453006  1.234431085  2.079115497 -0.040360175
    ## [126]  0.395743976  0.660860384 -0.836636175  0.249253035 -0.243086004
    ## [131] -0.329610582 -0.253815053 -0.579681157 -1.223256486  0.308478310
    ## [136] -0.884898575 -2.176591360 -0.163157204 -0.263735306  0.273042753
    ## [141] -1.107561811  1.404944033  1.447835819 -1.876965146  1.374055732
    ## [146]  0.705149696  0.336866349  0.433902936 -0.634370429 -1.309157240
    ## [151]  1.478370845  1.394084380 -2.554712189 -0.579740873 -1.159310197
    ## [156]  1.428679920  0.522239182 -0.255569713 -0.240859834 -0.459193831
    ## [161]  0.198899537 -1.364305781 -1.434015553  0.485703852 -0.621613350
    ## [166]  1.274019551 -1.852633436 -1.611185892  0.608796185  0.386794494
    ## [171]  0.896587474  0.238547059 -0.821349464 -0.074099713 -0.972724478
    ## [176]  0.718012491  0.744798761 -0.744069480  1.125333848 -1.057597961
    ## [181] -0.395479635  1.571920665  0.048382062 -0.455542561  0.466081777
    ## [186] -1.177513018 -0.254874413  1.828480885 -0.390746821  0.685769900
    ## [191] -0.185499111  0.008983621  1.476246004 -0.582439083  0.123076973
    ## [196]  2.388174014  0.467490284  1.284166659 -0.663028022 -1.086267524

## Problem 1b

``` r
np = function (size = 200, func) {
  boottest_boot = func()$teststatvec %>% 
    sample(size = 200, replace = TRUE)
  n = sum(boottest_boot > func()$bootpval)
  np = n/size
  return(np)
}

treffect_lower_paired = qnorm(.025, mean = mean(sample(paired_sample_df$diff, size = length(paired_sample_df$diff), replace = TRUE)))
treffect_upper_paired = qnorm(.025, mean = mean(sample(paired_sample_df$diff, size = length(paired_sample_df$diff), replace = TRUE)))

c(treffect_lower_paired, treffect_upper_paired)
```

    ## [1]  2.990036 -2.309964

The p-value for the paired samples is 0.24 and the p-value for the
two-sample data is 0.035, which shows a difference for different types
of patients.

The confidence interval for the effect size in paired data is (2.99,
-2.31), which is not what would be expected based on the p-values.

## in parallel

``` r
set.seed(22)
nCores <- detectCores() # detect numbers of available cores 
cl = makeCluster(nCores)
cl
```

    ## socket cluster with 8 nodes on host 'localhost'

``` r
system.time({
res2 = boottest_paired()
})
```

    ##    user  system elapsed 
    ##       0       0       0

``` r
stopCluster(cl)
```

## Problem 2

``` r
data(galaxies)
galaxies %>%
  as_tibble() %>% 
  ggplot(aes(x = value)) +
  geom_histogram()
```

    ## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

<img src="p8160_hw4_jsg2145_files/figure-gfm/unnamed-chunk-9-1.png" width="90%" />

``` r
plot(density(galaxies/1000, bw=1.5))
```

<img src="p8160_hw4_jsg2145_files/figure-gfm/unnamed-chunk-9-2.png" width="90%" />

``` r
plot(density(galaxies/1000, bw=3.5))
```

<img src="p8160_hw4_jsg2145_files/figure-gfm/unnamed-chunk-9-3.png" width="90%" />

``` r
#calculate the number of modes in the density
den <- density(galaxies/1000, bw=1.5)
den.s <- smooth.spline(den$x, den$y, all.knots = TRUE, spar = 0.8)
s.1 <- predict(den.s, den.s$x, deriv=1)
nmodes <- length(rle(den.sign <- sign(s.1$y))$values)/2
```

``` r
unif_dens = function(u){
  u = runif(82)
}

data = galaxies

x = rep(NA, 82)
for (i in 1:82) {
  x[i] = unif_dens(u)[[i]] %*% data[[i]]
}

h = (4 * min(sd(data), IQR(data))/(3*200))^(1/5)

kernel = function(x) {
  mean(unif_dens((x - data)/h))/h
}

kernel(x)
```

    ## [1] 0.2613537

``` r
kpdf = function(x) {
  sapply(x, kernel)
}

kpdf(x)
```

    ##  [1] 0.3052535 0.2904226 0.2335151 0.2551579 0.2429064 0.2685964 0.2361574
    ##  [8] 0.2394938 0.2825924 0.2802298 0.2708697 0.2496031 0.2575829 0.2727521
    ## [15] 0.2709521 0.2174171 0.2261209 0.2794149 0.2751300 0.2712368 0.2665116
    ## [22] 0.2971769 0.2816363 0.2699804 0.2377779 0.2655621 0.2413035 0.2437198
    ## [29] 0.2670400 0.2933334 0.2862980 0.2624176 0.2645550 0.2819202 0.2655556
    ## [36] 0.2793238 0.2593900 0.2589355 0.2578916 0.2742556 0.2446879 0.2467353
    ## [43] 0.2693671 0.2592562 0.2508607 0.2653156 0.2656719 0.2766899 0.2556559
    ## [50] 0.2687743 0.2530010 0.2517961 0.2666387 0.2662923 0.2830011 0.2692714
    ## [57] 0.2859677 0.2491910 0.2586846 0.2570340 0.2783758 0.2529073 0.2790781
    ## [64] 0.3028477 0.2775777 0.2732184 0.2826819 0.2810434 0.3095742 0.2784450
    ## [71] 0.2713188 0.2658945 0.2668400 0.2842546 0.2559046 0.2554585 0.2302489
    ## [78] 0.2740709 0.2565015 0.2725445 0.2365751 0.2502229

``` r
plot(x,unif_dens(x), type="l", col="red") 
par(new=T)
plot(x,kpdf(x),type="l",ylim=c(0,0.23),xlab="",ylab="",axes=F)
```

<img src="p8160_hw4_jsg2145_files/figure-gfm/unnamed-chunk-11-1.png" width="90%" />
